ccao-data/model-condo-avm

- README.Rmd
- README.md
This PR updates `README.Rmd` along similar lines as the changes in https://github.com/ccao-data/model-res-avm/pull/18 to remove references to legacy `ccao::vars_dict` attributes that were removed in https://github.com/ccao-data/ccao/pull/6. Instead of getting condo-specific attributes from the vars dict, we now pull the latest residential parameters from the `model-res-avm` repo and diff them against the condo params to generate the column marking condo-specific parameters.
> Remove legacy ccao::vars_dict attributes from README.Rmd code

- .github/workflows/build-and-run-model.yaml
- .renvignore
- Dockerfile
- Pipfile
- Pipfile.lock
- README.Rmd
- README.md
- dvc.yaml
- params.yaml
- pipeline/01-train.R
- pipeline/02-assess.R
- pipeline/03-evaluate.R
- pipeline/05-finalize.R
- renv.lock
This PR adds a new `build-and-run-model` workflow to build, run, and cleanup the model on GitHub Actions. The workflow is configured to run on PRs and workflow dispatch. On pushes to the main branch, the workflow will rebuild the container image for the main branch, but will not run or cleanup the model.
This PR mirrors the following PRs in `model-res-avm`:
* https://github.com/ccao-data/model-res-avm/pull/25
* https://github.com/ccao-data/model-res-avm/pull/59
Note also that in order to test a full model run, we switch to using the `loc_cook_municipality_name` feature instead of `loc_tax_municipality_name`. This is not actually the correct feature, and we'll need to switch it back in https://github.com/ccao-data/model-condo-avm/pull/4, but `loc_tax_municipality_name` is not yet present …
> Add Dockerfile and `build-and-run-model` workflow for CI model runs

- .github/workflows/build-and-run-model.yaml
Merging #9 revealed a bug in the `build-and-run-model.yaml` workflow: When calling a reusable workflow from an external repository, the ref for the workflow always needs to be defined in the `uses:` attribute ([SO source](https://stackoverflow.com/a/73026906)) ([example failed run](https://github.com/ccao-data/model-condo-avm/actions/runs/6870408711/workflow)).
For evidence that this works, note that the `build` step successfully loaded and ran in this workflow run: https://github.com/ccao-data/model-condo-avm/actions/runs/6870496545/job/18685510675?pr=11
> Bugfix: Pin `build-and-run-batch-job` workflow ref to `main`

- .github/workflows/build-and-run-model.yaml
This PR is the twin of https://github.com/ccao-data/model-res-avm/pull/64, fixing a bug to ensure that the model pipeline sends SNS status notifications.
Link to successful workflow run: https://github.com/ccao-data/model-condo-avm/actions/runs/7062881392/job/19227930519?pr=14 Check your email to confirm that the SNS notification was sent properly.
> Set SNS topic env var in `build-and-run-model` workflow container

- pipeline/07-export.R
Hot fix for `write_csv()` not being found while running export through dvc.
> Name-space `write_csv()`

- pipeline/07-export.R
This PR corrects an unintended change to the formatting of iasWorld output csv. Per Mirella:
> Condos – please batch by Township
> - PIN (PARID)
> - Card number (CARD)
> - Line number (LLINE)
> -  Full building market value (does not need to be prorated) – land is excluded
[Example template](https://github.com/ccao-data/model-condo-avm/files/14302523/TEMPLATE.-.RES.SFR.CONDO.xlsx).
We want to export the same total building improvement value (total building value - total building land value) for each PIN14 within that building.
> Revert switch to condo unit value iasworld upload

- pipeline/07-export.R
Buildings with no livable units will have values of zero assigned to all of their parcels. We don't want to export these zero values to iasWorld. This PR removes those parcels from the iasWorld export.
> Remove zero and `NA` value  parcels from iasWorld export

- README.Rmd
- README.md
- renv.lock
This PR finalizes the residential model README following the 2024 model. It links to final residential model data, a new 2024-assessment-year tag, and relevant issue. It slightly updates the copy where applicable.
> Finalize README for 2024

- pipeline/03-evaluate.R
This PR updates the `evaluate` stage of the pipeline to switch from the [multisession](https://future.futureverse.org/reference/multisession.html) parallelization strategy to [multicore](https://future.futureverse.org/reference/multicore.html). This change is intended to fix the behavior we've been seeing on the server whereby the `evaluate` stage takes so long to complete that it makes development difficult.
I'm not sure why this behavior appears to be different from last year, but my experiments with trying different numbers of workers using the "multisession" strategy on a minimal reprex revealed that execution begins to slow down when the number of workers increases past 5 (minimum runtime ~10 minutes). There must be some sort of overhead that the background R processes incur, but I …
> Switch from multisession parallelization to multicore in `evaluate` stage

- dvc.lock
This PR updates our `dvc.lock` file so that stages after `00-ingest` accurately reflect the results of a full `dvc repro` command.
The basic issue here is that after wrapping the 2024 condo model, I committed the final data to _only_ the `00-ingest` stage without propagating that data to any of the downstream stages (by running a full `dvc repro`). This resulted in DVC creating large `dvc.lock` diffs for any model run, regardless of whether input parameters or data were changed (compared to the final 2024 model).
The updates to `dvc.lock` should accurately reflect the state of the pipeline had we run it immediately after finalizing the 2024 model (minus any weird effects caused by KNN ala #54).
@wagnerlmichael 
Unblocks #52.
> Update dvc.lock file to reflect `2024-assessment-year` tag data

- pipeline/00-ingest.R
This PR [standardizes](https://github.com/ccao-data/model-sales-val/blob/a60618004e85dd53a5e0decec481fa797ec680a0/glue/sales_val_flagging.py#L240-L246) the manually assigned outlier names from the `00-ingest.R` stage. The existing method was an artifact from the older sales val specifications.
Closes #59
> Standardize outlier reason names

- Dockerfile
- renv.lock
- renv/activate.R
- renv/profiles/dev/renv.lock
- renv/profiles/reporting/renv.lock
This PR is the companion to https://github.com/ccao-data/model-res-avm/pull/262, bumping R dependencies used by the condo model to their most recent versions.
While https://github.com/ccao-data/model-res-avm/pull/262 needed to adjust the `ingest` stage to reflect a deprecation in the `tidyselect` interface, this PR does not do so, because the `process_array_columns` function doesn't exist in the condo model.
I did not test a full `repro` as part of this update, but I'm happy to do so if you think it's important.
> Update R dependencies

- .github/workflows/build-and-run-model.yaml
- .pre-commit-config.yaml
- dvc.yaml
- params.yaml
- pipeline/00-ingest.R
- pipeline/03-evaluate.R
This PR is the condo model version of https://github.com/ccao-data/model-res-avm/pull/278, making a few small aesthetic tweaks:
* Linting all YAML files
* Suppressing certain warnings in the evaluate stage
We don't need to duplicate the functional changes that we made in https://github.com/ccao-data/model-res-avm/pull/278 since the condo model:
* Never had a `_quarto.yml` file
* Never used land site rates
Output of `yamllint .` after these changes:
```
./.pre-commit-config.yaml
3:1       warning  missing document start "---"  (document-start)
./params.yaml
14:1      warning  missing document start "---"  (document-start)
./dvc.yaml
1:1       warning  missing document start "---"  (document-start)
./.github/workflows/build-and-run-model.yaml
10:1      warning  missing document start "---" …
```
> Lint YAML files and suppress warnings in the evaluate stage

- .github/workflows/build-and-run-model.yaml
- .github/workflows/pre-commit.yaml
This PR creates parity with https://github.com/ccao-data/model-res-avm/pull/286.
> Consider assessment year branches to be main branches in GitHub workflows

- R/helpers.R
- dvc.lock
- pipeline/00-ingest.R
- renv/profiles/dev/renv.lock
- renv/profiles/reporting/renv.lock
A few updates here to reflect the changes from https://github.com/ccao-data/model-res-avm/pull/283, as well as catch the condo model up on the `unload = TRUE` option of `noctua`.
> Update 2025 input data

- reports/performance/_outliers.qmd
This PR adds more outlier information and makes a number of small improvements.
> Add info from outlier reason 2 and clean up graphs

- pipeline/03-evaluate.R
Same as https://github.com/ccao-data/model-res-avm/pull/299.
> Fix missing `geography_id` for triads

- R/setup.R
Sets the global R seed for use in the Tidymodels CV loop and KNN resampling. Does _not_ affect the RNG of the model (LightGBM) itself. Tested by running two runs in a row and checking the DVC lockfile after each run (only the timing outputs changed).
Setting the global seed to control Tidymodels RNG didn't work in the past. They must have updated the `tune` library at some point to respect `set.seed()`.
Fixes #61.
> Set global R seed inside `R/setup.R`

- reports/performance/_outliers.qmd
As found in https://github.com/ccao-data/model-condo-avm/pull/78, NULL and NA values are often present in the Condo Pipeline. This provides counts for those values in the outliers section.
> Add test for NA or NULL values

- pipeline/00-ingest.R
The `sv_outlier_reason1` field was empty when we should have observed a non-livable description. For some reason we were using arrows instead of equal signs in the mutate assignment. We replace them and the outlier reason assignment is now fixed.
> Replace arrows with equal signs for outlier assignment

- pipeline/05-finalize.R
Same as https://github.com/ccao-data/model-res-avm/pull/316.
> Unset the random seed for run ID generation

- renv.lock
Follow-up from https://github.com/ccao-data/ccao/pull/35.
> Bump ccao package version

- params.yaml
- pipeline/03-evaluate.R
Currently, 2024 PUMA geographies are all `NULL` since we haven't correctly attached them via the spatial join in `location.census`. This results in us dropping all 2024 sales from the test set evaluation.
We'll fix the data issue upstream via dbt builds, but in the meantime I think it's best to just remove this filter, since we almost never look at performance on the PUMA level.
> Remove PUMA filter on test set eval
